# API Keys and Secrets
# WARNING: This file contains sensitive information. Do not commit to version control!

data_providers:
  alphavantage:
    api_key: "991AR2LC298IGMX7"
    
  # Add other API keys as needed
  # polygon:
  #   api_key: "your_polygon_key"
  # quandl:
  #   api_key: "your_quandl_key"