# Base configuration for AlgoStack

engine:
  mode: paper  # paper, live
  log_level: INFO
  
data:
  providers:
    - yfinance
    - alpha_vantage
  cache_dir: data/cache
  
portfolio:
  initial_capital: 5000.0
  base_currency: USD
  
risk:
  target_vol: 0.10  # 10% annual volatility
  max_position_size: 0.25  # Max 25% per position
  max_drawdown: 0.15  # 15% kill switch
  kelly_fraction: 0.5  # Half-Kelly sizing
  stop_loss_atr: 3.0
  
strategies:
  mean_reversion:
    enabled: true
    symbols:
      - SPY
      - QQQ
      - IWM
      - DIA
    params:
      rsi_period: 2
      rsi_oversold: 10
      atr_band_mult: 2.5
      
  trend_following:
    enabled: true
    symbols:
      - MES  # Micro E-mini S&P
      - MNQ  # Micro E-mini Nasdaq
      - BTC-USD  # Bitcoin
      - ETH-USD  # Ethereum
    params:
      channel_period: 20
      trail_period: 10
      atr_period: 14
      adx_period: 14
      adx_threshold: 25
      use_volume_filter: true
      volume_threshold: 1.2
      
  pairs_stat_arb:
    enabled: false
    symbols: []  # Will be populated with pairs
    params:
      lookback_period: 90
      zscore_window: 30
      entry_threshold: 2.0
      exit_threshold: 0.2
      adf_pvalue: 0.05
      max_pairs: 5
      
  intraday_orb:
    enabled: false
    symbols:
      - SPY
      - QQQ
    params:
      opening_minutes: 30
      volume_threshold: 1.5
      atr_filter: 0.5
      breakout_buffer: 0.001  # 0.1%
      
  overnight_drift:
    enabled: false
    symbols:
      - SPY
      - QQQ
    params:
      hold_days: ["Monday", "Tuesday", "Wednesday", "Thursday"]
      vix_threshold: 30
      trend_filter: true
      sma_period: 50
      
  hybrid_regime:
    enabled: false
    symbols:
      - SPY
      - QQQ
      - IWM
      - DIA
    params:
      regime_window: 20
      adx_threshold: 25
      bb_width_threshold: 0.15
      allocation_mr: 0.6
      allocation_tf: 0.6
      
execution:
  broker: paper  # paper, ibkr, robinhood
  order_timeout_seconds: 60
  retry_attempts: 3
  
alerts:
  email:
    enabled: false
    smtp_server: smtp.gmail.com
    smtp_port: 587
    from_email: algostack@example.com
    to_emails:
      - trader@example.com
      
  discord:
    enabled: false
    webhook_url: ""
    
backtest:
  start_date: "2020-01-01"
  end_date: "2023-12-31"
  initial_capital: 5000
  commission: 0.0  # Zero commission
  slippage: 0.0005  # 0.05% slippage